### ISSUE TITLE
GitLab CI Install Own Server

### ISSUE THREAD

**Issue by iolson** [bobey/docker-gitlab-ci-runner#13]
I was wondering what would be the steps to install your image via the Runner CLI command while running my own GitLab CI instance. The following questions are asked:
- Please enter the executor: docker-ssh, ssh, shell, parallels, docker:
- Please enter the Docker image (eg. ruby:2.1):
- If you want to enable mysql please enter version (X.Y) or enter latest?
- If you want to enable postgres please enter version (X.Y) or enter latest?
- If you want to enable redis please enter version (X.Y) or enter latest?
- If you want to enable mongo please enter version (X.Y) or enter latest?

I just want to make sure I can use your images that you have created, and then I would just upload with the `.gitlab-ci.yml` file correct with my `composer install` and `php vendor/phpunit/phpunit/phpunit --coverage-text` commands?

Or would I setup my .yml file like the example here: http://doc.gitlab.com/ci/yaml/README.html

Sorry I'm used to Travis and Scrutinizer, but I'm setting this up to do private builds.

Thank you in advance!

**Comment by iolson** [comment]
Small update, I'm getting further along. https://gist.github.com/iolson/2c6941c9780b1ebcc25f

But now stuck on connecting to MySQL server container :/

**Comment by raftalks** [comment]
@iolson exactly the same issue I have. Hope to see some light for this issue. :+1:

**Comment by obalais** [comment]
@iolson @raftalks Please be aware that this project is deprecated since Gitlab released its own Docker Runner : https://gitlab.com/gitlab-org/gitlab-ci-multi-runner

**Comment by iolson** [comment]
I got this working with MySQL container with the gitlab multi runner @raftalks - the DB host should be setup with: mysql 

This is an non-issue now.

**Comment by raftalks** [comment]
@iolson can you share with me gitlab-ci.yml setup done with gitlab-ci-multi-runner, as it is the same runner that I was using but had similar issue like yours.

**Comment by iolson** [comment]
@raftalks https://gist.github.com/iolson/a60c5f238b90f411bec3
