### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by mintbridge** [bobey/docker-gitlab-ci-runner#14]
Thanks for the work on this!

Is this a PHP7 image on the cards?

**Comment by obalais** [comment]
Hi,

Thanks for your feedback.
In fact, I do not maintain this repository anymore since Gitlab released its very own MultiRunner setup with Docker support.

More information here: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner

**Comment by mintbridge** [comment]
Sorry wrong repo, but iwas meaning a docker build for PHP7 https://hub.docker.com/r/bobey/docker-gitlab-ci-runner-php/
